### ISSUE TITLE
Comment on re-subscribe on connect

### ISSUE THREAD

**Issue by hobbyquaker** [dersimn/node-mqtt-smarthome#1]
https://github.com/dersimn/node-mqtt-smarthome/blob/df548d6adb1097b8fb9ff792e7281f959cb49054/index.js#L98

In the past I implemented that in my xy2mqtt daemons, but I think it should not be necessary anymore, MQTT.js's client handles that (if using their reconnection mechanism):
```
resubscribe : if connection is broken and reconnects, subscribed topics are automatically subscribed again (default true)
```

**Comment by dersimn** [comment]
Thanks👍🏻
