### ISSUE TITLE
Comment on incoming message handler

### ISSUE THREAD

**Issue by hobbyquaker** [dersimn/node-mqtt-smarthome#3]
https://github.com/dersimn/node-mqtt-smarthome/blob/df548d6adb1097b8fb9ff792e7281f959cb49054/index.js#L47

The emitted events and callbacks should also provide the raw message object as third param as received from MQTT.js. This opens the possibility to use message flags, e.g. in some of my interfaces it's of relevance if a message is received from a retained topic or not.

**Comment by dersimn** [comment]
This [one](https://github.com/mqttjs/MQTT.js#event-message) `packet` ?

**Comment by hobbyquaker** [comment]
yes
