### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by hobbyquaker** [dersimn/node-mqtt-smarthome#4]
Hi Simon!

Cool that you started this project. A module like this has been a point on my todo for too long, will start using yours in my daemons asap. Depending on how much time I find I will also contribute to this as much as needed/wanted :-) One wish I have: can we agree on using https://github.com/sindresorhus/xo as codestyle/linter?

Regards,
Sebastian

**Comment by dersimn** [comment]
I like that tool, never heard of it before though.

Maybe you can explain what these errors are for:
![bildschirmfoto 2017-12-24 um 10 46 58](https://user-images.githubusercontent.com/3258452/34325654-20f6ddf0-e898-11e7-9d70-513f178d9fe4.png)

**Comment by hobbyquaker** [comment]
you can find explanations to the rules here: https://eslint.org/docs/rules, e.g. https://eslint.org/docs/rules/eqeqeq

**Comment by hobbyquaker** [comment]
see also comment on https://github.com/dersimn/node-mqtt-smarthome/commit/09a659e8def5bc950ec12676d484d84e8283e8a0 about comparison with `null`

**Comment by hobbyquaker** [comment]
another suggestions for the `guard-for-in` thing: I stopped using `for ... in`, I stick with `Object.keys(obj).forEach(key => ...)`.
