### ISSUE TITLE
MQTT Topic matching suggestion

### ISSUE THREAD

**Issue by hobbyquaker** [dersimn/node-mqtt-smarthome#5]
https://github.com/dersimn/node-mqtt-smarthome/blob/89c575cbfbb83ddf27db1ebdd76f386f82c2e6ea/index.js#L71

I would suggest to use https://github.com/hobbyquaker/mqtt-wildcard for the MQTT topic matching

Best Regards, Sebastian

**Comment by dersimn** [comment]
Yeah, sure. Sounds good.

**Comment by hobbyquaker** [comment]
implemented that in #6 
Think it's better to stick with a pull-request workflow, 4 eyes see more than 2 ;-)
